# Generated by Django 4.1.4 on 2022-12-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticapp', '0002_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Teams',
        ),
    ]
