# Generated by Django 4.1.4 on 2022-12-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticapp', '0003_rename_team_teams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
